### ISSUE TITLE
physiochemical module

### ISSUE THREAD

**Issue by shoy91** [xidan21/PASE#1]
Hi!

I was looking at your physiochemical script that calculates score when you change an amino acid. You have this line: 
changing_value = math.sqrt(sum)*0.0872

I was wondering why you multiplied the result by .0872? This isn't part of the euclidean distance formula. 

Thanks,
Sohini

**Comment by xidan21** [comment]
Dear Sohini,


The code "multiplied the result by .0872" is to normalise the result, which is the maximum value divided by 1. It is long time ago, I cann't remember what the maximum value is, but the purpose of this step to normalise the result value so that its range is between 0 and 1.


Best,


Xidan


________________________________

**Comment by shoy91** [comment]
makes sense thanks!
